name: second_github_action
on: [push]
jobs:
  aws_cp:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.awsaccesskeyid }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
          aws-region: ap-south-1
      - name: Upload to s3
        run: aws s3 cp ./app.py s3://venckat-demo-bucket
